use crate::error::AppError;
use crate::models::job::{JobProgress, JobState, PipelineEvent, RenderJob};
use crate::utils::event;
use serde::Serialize;
use std::path::Path;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use tauri::AppHandle;

/// Minimum gap (ms) between coalesced progress emissions sent to the frontend.
/// ffmpeg emits progress lines several times per second per concurrent job, so
/// without throttling the pipeline would clone + serialize the entire job list
/// on every line.
const EMIT_INTERVAL_MS: u64 = 120;

/// Light-weight job representation for state serialisation — excludes the
/// `timestamps` vector to keep the state file small. Timestamps can grow to
/// 90 000+ entries per job for renders with many loop repeats; they are
/// regenerated by `process_single_job` on resume.
#[derive(Serialize)]
struct RenderJobState {
    video: crate::models::media::VideoFile,
    state: JobState,
    progress_percent: u8,
    current_step: String,
    error: Option<String>,
}

/// Manages render-state persistence and progress emission for the pipeline.
pub struct StateManager {
    last_save_sec: AtomicU64,
    last_emit_ms: AtomicU64,
}

impl StateManager {
    pub fn new() -> Self {
        Self {
            last_save_sec: AtomicU64::new(0),
            last_emit_ms: AtomicU64::new(0),
        }
    }

    pub async fn save_state(&self, state_path: &Path, jobs: &[RenderJob]) -> Result<(), AppError> {
        let state_jobs: Vec<RenderJobState> = jobs
            .iter()
            .map(|j| RenderJobState {
                video: j.video.clone(),
                state: j.state.clone(),
                progress_percent: j.progress_percent,
                current_step: j.current_step.clone(),
                error: j.error.clone(),
            })
            .collect();
        self.save_state_jobs(state_path, &state_jobs).await
    }

    async fn save_state_jobs(&self, state_path: &Path, state_jobs: &[RenderJobState]) -> Result<(), AppError> {
        let json = serde_json::to_string(state_jobs).map_err(|e| AppError::Pipeline(e.to_string()))?;
        let state_path = state_path.to_path_buf();
        let temp_path = state_path.with_extension("tmp");
        tokio::task::spawn_blocking(move || {
            use std::io::Write;
            let mut file = std::fs::File::create(&temp_path).map_err(|e| AppError::Pipeline(e.to_string()))?;
            file.write_all(json.as_bytes()).map_err(|e| AppError::Pipeline(e.to_string()))?;
            file.sync_all().map_err(|e| AppError::Pipeline(e.to_string()))?;
            std::fs::rename(&temp_path, &state_path).map_err(|e| AppError::Pipeline(e.to_string()))?;
            Ok(())
        })
        .await
        .map_err(|e| AppError::Pipeline(format!("spawn_blocking panicked: {}", e)))?
    }

    pub async fn save_state_from_arc(
        &self,
        state_path: &Path,
        jobs_arc: &Arc<tokio::sync::Mutex<Vec<RenderJob>>>,
    ) -> Result<(), AppError> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        let last = self.last_save_sec.load(Ordering::Acquire);
        if now.saturating_sub(last) < 2 {
            return Ok(());
        }
        // Use compare_exchange to avoid double-save when two concurrent callers
        // race through the guard above. Only one caller succeeds; the other
        // bails out, avoiding a redundant disk write.
        if self
            .last_save_sec
            .compare_exchange(last, now, Ordering::SeqCst, Ordering::Acquire)
            .is_err()
        {
            return Ok(());
        }
        // Build the lightweight serialisable snapshot while holding the lock,
        // then release it before the blocking file write to avoid stalling
        // progress updates.
        let state_jobs: Vec<RenderJobState> = {
            let jobs = jobs_arc.lock().await;
            jobs.iter()
                .map(|j| RenderJobState {
                    video: j.video.clone(),
                    state: j.state.clone(),
                    progress_percent: j.progress_percent,
                    current_step: j.current_step.clone(),
                    error: j.error.clone(),
                })
                .collect()
        };
        self.save_state_jobs(state_path, &state_jobs).await
    }

    pub async fn emit_progress_from_arc(
        &self,
        app: &AppHandle,
        jobs_arc: &Arc<tokio::sync::Mutex<Vec<RenderJob>>>,
    ) {
        let jobs = jobs_arc.lock().await;
        let total = jobs.len();
        let completed = jobs.iter().filter(|j| j.state == JobState::Done).count();
        // Send a compact per-job payload instead of cloning the full `RenderJob`
        // (which would also drag along each job's `timestamps` vector). Only the
        // fields the dashboard needs for the table + progress bar are included.
        let progress: Vec<JobProgress> = jobs
            .iter()
            .enumerate()
            .map(|(i, j)| JobProgress {
                index: i,
                state: j.state.clone(),
                progress_percent: j.progress_percent,
                current_step: j.current_step.clone(),
                name: j.video.name.clone(),
                output_path: j.video.output_path.clone(),
                thumbnail_path: j.video.thumbnail_path.clone(),
            })
            .collect();
        drop(jobs);
        event::emit(
            app,
            PipelineEvent::Progress {
                total,
                completed,
                jobs: progress,
            },
        );
    }

    /// Like [`Self::emit_progress_from_arc`] but coalesces bursts: at most one
    /// emission per [`EMIT_INTERVAL_MS`] window. Used for the high-frequency,
    /// per-frame ffmpeg progress updates so we don't clone + serialize the job
    /// list dozens of times per second.
    pub async fn emit_progress_throttled(
        &self,
        app: &AppHandle,
        jobs_arc: &Arc<tokio::sync::Mutex<Vec<RenderJob>>>,
    ) {
        let now_ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;
        let last = self.last_emit_ms.load(Ordering::Acquire);
        if now_ms.saturating_sub(last) < EMIT_INTERVAL_MS {
            return;
        }
        if self
            .last_emit_ms
            .compare_exchange(last, now_ms, Ordering::SeqCst, Ordering::Acquire)
            .is_err()
        {
            return;
        }
        self.emit_progress_from_arc(app, jobs_arc).await;
    }
}

impl Default for StateManager {
    fn default() -> Self {
        Self::new()
    }
}
